changes  for zimbra

diff --git a/tools/build-release-tarball b/tools/build-release-tarball
--- a/tools/build-release-tarball
+++ b/tools/build-release-tarball
@@ -1,9 +1,6 @@
 #!/usr/bin/env bash
 set -eu
 
-# shellcheck source=lib/git-tools.bash
-. "$(dirname "$0")"/lib/git-tools.bash
-
 usage() {
     echo "Usage: $0 <ZULIP_VERSION>" >&2
     exit 1
@@ -29,10 +26,18 @@ fi
 version="$1"
 prefix="zulip-server-$version"
 
-require_clean_work_tree 'build a release tarball'
-
 set -x
 GITID=$(git rev-parse HEAD)
+
+if ! git diff --exit-code >/dev/null; then
+    set +x
+    echo "ERROR: tarballs builds are based on a commit hash so your changes "
+    echo "will not be included; you should commit or stash them based on "
+    echo "what you want and then try again."
+    echo
+    git diff
+    exit 1
+fi
 
 umask 022
 
@@ -44,9 +49,53 @@ git archive -o "$TARBALL" "--prefix=$prefix/" HEAD
 
 cd "$TMPDIR"
 tar -xf "$TARBALL"
+
+if [ -f /etc/os-release ]; then
+    os_info="$(
+        . /etc/os-release
+        printf '%s\n' "$ID" "$VERSION_ID"
+    )"
+    {
+        read -r os_id
+        read -r os_version_id
+    } <<<"$os_info"
+fi
+
+SYS_DEPS_NAME=""
+# copy depandencies
+if [ $os_id == "centos" ] && [[ "$os_version_id" == 7* ]]; then
+    PY_DEPS_NAME=centos
+    PY_DEPS_VERSION=7
+    SYS_DEPS_NAME=centos7
+    export LC_CTYPE=en_US.UTF-8
+elif [ $os_id == "ubuntu" ] && [[ "$os_version_id" == 18* ]]; then
+    PY_DEPS_NAME=ubuntu
+    PY_DEPS_VERSION=18
+else 
+    PY_DEPS_NAME=ubuntu
+    PY_DEPS_VERSION=20
+fi
+
+PY_DEPS_PATH=${TMPDIR:?}/$prefix/packages/py-deps/
+mkdir -p $PY_DEPS_PATH
+cp -a "${TMPDIR:?}/$prefix/packages/all-py-deps/$PY_DEPS_NAME/$PY_DEPS_VERSION/." "$PY_DEPS_PATH"
+
+if [ -n "$SYS_DEPS_NAME" ]; then
+    SYS_DEPS_PATH=${TMPDIR:?}/$prefix/packages/sys-deps/
+    mkdir -p $SYS_DEPS_PATH
+    cp -a "${TMPDIR:?}/$prefix/packages/all-system-deps/$SYS_DEPS_NAME/." "$SYS_DEPS_PATH"
+fi
+
+# override zimbra related changes
+rsync -av "${TMPDIR:?}/$prefix/zimbra/" "${TMPDIR:?}/$prefix/"
+
 while read -r i; do
     rm -r --interactive=never "${TMPDIR:?}/$prefix/$i"
 done <"$TMPDIR/$prefix/tools/release-tarball-exclude.txt"
+
+
+
+
 tar -cf "$TARBALL" "$prefix"
 rm -rf "$prefix"
 
