install file changed

diff --git a/zimbra/scripts/lib/install b/zimbra/scripts/lib/install
--- a/zimbra/scripts/lib/install
+++ b/zimbra/scripts/lib/install
@@ -28,10 +28,6 @@ Options:
       install process; used when this command is run once in a highly-controlled
       environment to produce an image which is used elsewhere.  Uncommon.
 
-  --postgresql-database-name=zulip
-      Sets the PostgreSQL database name.
-  --postgresql-database-user=zulip
-      Sets the PostgreSQL database user.
   --postgresql-version=13
       Sets the version of PostgreSQL that will be installed.
   --postgresql-missing-dictionaries
@@ -51,7 +47,7 @@ EOF
 
 # Shell option parsing.  Over time, we'll want to move some of the
 # environment variables below into this self-documenting system.
-args="$(getopt -o '' --long help,hostname:,email:,certbot,self-signed-cert,cacert:,postgresql-database-name:,postgresql-database-user:,postgresql-version:,postgresql-missing-dictionaries,no-init-db,no-overwrite-settings,no-dist-upgrade -n "$0" -- "$@")"
+args="$(getopt -o '' --long help,hostname:,email:,ldap-server:,ldap-password:,ldap-bind-dn:,certbot,self-signed-cert,cacert:,postgresql-version:,postgresql-missing-dictionaries,no-init-db,no-overwrite-settings,no-dist-upgrade -n "$0" -- "$@")"
 eval "set -- $args"
 while true; do
     case "$1" in
@@ -84,16 +80,7 @@ while true; do
             SELF_SIGNED_CERT=1
             shift
             ;;
-        --postgresql-database-name)
-            POSTGRESQL_DATABASE_NAME="$2"
-            shift
-            shift
-            ;;
-        --postgresql-database-user)
-            POSTGRESQL_DATABASE_USER="$2"
-            shift
-            shift
-            ;;
+
         --postgresql-version)
             POSTGRESQL_VERSION="$2"
             shift
@@ -201,13 +188,15 @@ if [[ "$LDAP_SERVER_PORT"  == "" ]]; then
     LDAP_SERVER_PORT=389
 fi
 
-while true; do
-    echo -n "Please enter LDAP password: "
-    read LDAP_PASSWORD
-    if [[ "$LDAP_PASSWORD"  != "" ]]; then
-        break
-    fi
-done 
+if [[ "$LDAP_PASSWORD"  == "" ]]; then
+    while true; do
+        echo -n "Please enter LDAP password: "
+        read LDAP_PASSWORD
+        if [[ "$LDAP_PASSWORD"  != "" ]]; then
+            break
+        fi
+    done
+fi
 
 echo -n "Please enter LDAP bind dn (default - uid=zimbra,cn=admins,cn=zimbra): "
 read LDAP_BIND_DN
@@ -302,8 +291,8 @@ case "$os_id$os_version_id" in
 Unsupported OS release: $os_id $os_version_id
 
 Zulip in production is supported only on:
- - Debian 10 "buster"
  - Debian 11 "bullseye" (beta)
+ - Debian 10 "buster"
  - Ubuntu 18.04 LTS "bionic"
  - Ubuntu 20.04 LTS "focal"
 
@@ -313,6 +302,29 @@ EOF
         exit 1
         ;;
 esac
+
+# Force a known locale.  Some packages on PyPI fail to install in some locales.
+if [ "$os_id" = centos ]; then
+    export LC_ALL="en_US.UTF-8"
+    export LANG="en_US.UTF-8"
+    export LANGUAGE="en_US.UTF-8"
+    POSTGRESQL_VERSION="10"
+
+    # Create certificate and put it to the right place
+    mkdir -p /etc/ssl/private
+    openssl req -nodes -newkey rsa:2048 -days 3650 -keyout /etc/ssl/private/ssl-cert-snakeoil.key -out /etc/ssl/certs/ssl-cert-snakeoil.pem -subj "/C=IN/ST=MH/L=PN/O=Zulip/OU=Dev/CN=$EXTERNAL_HOST/emailAddress=$ZULIP_ADMINISTRATOR"
+    if grep -q "ssl-cert" /etc/group
+     then
+        echo "ssl-cert group already exists"
+     else
+        groupadd ssl-cert
+    fi
+    chown root:ssl-cert /etc/pki/tls/private
+else
+    export LC_ALL="C.UTF-8"
+    export LANG="C.UTF-8"
+    export LANGUAGE="C.UTF-8"
+fi
 
 if [ "$os_id" = ubuntu ] && ! apt-cache policy \
     | grep -q "^     release v=$os_version_id,o=Ubuntu,a=$os_version_codename,n=$os_version_codename,l=Ubuntu,c=universe"; then
@@ -377,13 +389,38 @@ if [ "$mem_kb" -lt 1860000 ]; then
     exit 1
 fi
 
+if [ "$package_system" = apt ]; then
+    # Note that any additions to these lists must also be added to
+    # `zulip::profile::base` such that the new dependency is seen by
+    # upgrades, as well as new installs.
+    if ! apt-get install -y \
+        python3 python3-yaml puppet git curl wget jq crudini \
+        "${ADDITIONAL_PACKAGES[@]}"; then
+        set +x
+        echo -e '\033[0;31m' >&2
+        echo "Installing packages failed; is network working and (on Ubuntu) the universe repository enabled?" >&2
+        echo >&2
+        echo -e '\033[0m' >&2
+        exit 1
+    fi
+elif [ "$package_system" = yum ]; then
+    if ! yum install -y \
+        python36 python36-PyYAML git curl wget jq crudini \
+        "${ADDITIONAL_PACKAGES[@]}"; then
+        set +x
+        echo -e '\033[0;31m' >&2
+        echo "Installing packages failed; is network working?" >&2
+        echo >&2
+        echo -e '\033[0m' >&2
+        exit 1
+    fi
+fi
+
 # Do package update, e.g. do `apt-get update` on Debian
 if [ "$package_system" = apt ]; then
     # setup-apt-repo does an `apt-get update`
     "$ZULIP_PATH"/scripts/lib/setup-apt-repo
 elif [ "$package_system" = yum ]; then
-    export LC_ALL=en_US.UTF-8
-    export LANG=en_US.UTF-8
     "$ZULIP_PATH"/scripts/lib/setup-yum-repo
 fi
 
@@ -423,33 +460,6 @@ if [ -z "$NO_DIST_UPGRADE" ]; then
     fi
 fi
 
-if [ "$package_system" = apt ]; then
-    # Note that any additions to these lists must also be added to
-    # `zulip::profile::base` such that the new dependency is seen by
-    # upgrades, as well as new installs.
-    if ! apt-get install -y \
-        python3 python3-yaml puppet git curl jq crudini \
-        "${ADDITIONAL_PACKAGES[@]}"; then
-        set +x
-        echo -e '\033[0;31m' >&2
-        echo "Installing packages failed; is network working and (on Ubuntu) the universe repository enabled?" >&2
-        echo >&2
-        echo -e '\033[0m' >&2
-        exit 1
-    fi
-elif [ "$package_system" = yum ]; then
-    if ! yum install -y \
-        python3 python3-pyyaml puppet git curl jq crudini \
-        "${ADDITIONAL_PACKAGES[@]}"; then
-        set +x
-        echo -e '\033[0;31m' >&2
-        echo "Installing packages failed; is network working?" >&2
-        echo >&2
-        echo -e '\033[0m' >&2
-        exit 1
-    fi
-fi
-
 if [ -n "$USE_CERTBOT" ]; then
     "$ZULIP_PATH"/scripts/setup/setup-certbot \
         --no-zulip-conf --method=standalone \
@@ -465,7 +475,17 @@ if [ "$VIRTUALENV_NEEDED" = "yes" ]; then
 fi
 
 "$ZULIP_PATH"/scripts/lib/install-node
-"$ZULIP_PATH"/scripts/lib/install-yarn
+
+if [ "$os_id" = centos ]; then
+    if [ -e /var/lib/puppet/classes.txt ]
+    then
+        echo "/var/lib/puppet/classes.txt file exists!"
+    else
+        mkdir -p /var/lib/puppet
+        touch /var/lib/puppet/classes.txt
+    fi
+fi
+
 
 # Generate /etc/zulip/zulip.conf .
 mkdir -p /etc/zulip
@@ -510,16 +530,8 @@ EOF
 
     # We only need the PostgreSQL version setting on database hosts; but
     # we don't know if this is a database host until we have the catalog summary.
-    if ! has_class "zulip::postgresql_common" || [ "$package_system" != apt ]; then
+    if ! has_class "zulip::postgresql_common"; then
         crudini --del /etc/zulip/zulip.conf postgresql
-    fi
-
-    if [ -n "$POSTGRESQL_DATABASE_NAME" ]; then
-        crudini --set /etc/zulip/zulip.conf postgresql database_name "$POSTGRESQL_DATABASE_NAME"
-    fi
-
-    if [ -n "$POSTGRESQL_DATABASE_USER" ]; then
-        crudini --set /etc/zulip/zulip.conf postgresql database_user "$POSTGRESQL_DATABASE_USER"
     fi
 
     # Note: there are four dpkg-query outputs to consider:
@@ -544,6 +556,100 @@ EOF
 nodename = zulip@localhost
 EOF
     fi
+fi
+
+DATA_DIR=/opt/zimbra/data/zulip
+POSTGRESQL_DIR=$DATA_DIR/postgresql
+RABBITMQ_DIR=$DATA_DIR/rabbitmq
+RABBITMQ_CONF_PATH=/etc/rabbitmq/rabbitmq-env.conf
+ZULIP_UPLOAD_DIR=/home/zulip/uploads
+ZIMBRA_ZULIP_UPLOAD_DIR=$DATA_DIR/uploads
+
+if [ $os_id == "ubuntu" ] || [ $os_id == "debian" ]; then
+    POSTGRESQL_DEFAULT_DATA_DIR=/var/lib/postgresql/$POSTGRESQL_VERSION
+    POSTGRESQL_DATA_DIR=$POSTGRESQL_DIR/$POSTGRESQL_VERSION/main
+    POSTGRESQL_CONF_PATH=/etc/postgresql/$POSTGRESQL_VERSION/main/postgresql.conf
+elif [ $os_id == "centos" ]; then
+    POSTGRESQL_DEFAULT_DATA_DIR=/var/lib/pgsql/$POSTGRESQL_VERSION
+    POSTGRESQL_DATA_DIR=$POSTGRESQL_DIR/$POSTGRESQL_VERSION/data
+    POSTGRESQL_CONF_PATH=/var/lib/pgsql/$POSTGRESQL_VERSION/data/postgresql.conf
+fi
+
+
+if [ ! -d "$DATA_DIR" ]; then 
+    echo "Create directory $DATA_DIR"
+    mkdir -p "$DATA_DIR"
+fi
+
+if [ ! -d "$POSTGRESQL_DATA_DIR" ]; then
+    echo "Create directory $POSTGRESQL_DATA_DIR"
+    mkdir -p "$POSTGRESQL_DATA_DIR"
+fi
+
+if [ ! -d "$RABBITMQ_DIR" ]; then
+    echo "Create directory $RABBITMQ_DIR"
+    mkdir -p "$RABBITMQ_DIR"
+fi
+
+if [ ! -d "$ZIMBRA_ZULIP_UPLOAD_DIR" ]; then
+    echo "Create directory $ZIMBRA_ZULIP_UPLOAD_DIR"
+    mkdir -p "$ZIMBRA_ZULIP_UPLOAD_DIR"
+fi
+
+if [ ! -d "$DATA_DIR/conf/" ]; then
+    echo "Create directory $DATA_DIR/conf/"
+    mkdir -p $DATA_DIR/conf/
+fi
+
+# change upload data path
+chown zulip:zulip $ZIMBRA_ZULIP_UPLOAD_DIR
+ln -nsf $ZIMBRA_ZULIP_UPLOAD_DIR $ZULIP_UPLOAD_DIR
+
+if [ "$os_id" = ubuntu ]; then
+  if which psql >/dev/null; then 
+    echo "Postgresql is already intalled";
+  else
+    apt-get install -y postgresql-$POSTGRESQL_VERSION
+  fi
+
+  if [[ ! -f "$POSTGRESQL_DATA_DIR/PG_VERSION" ]]; then
+    chown -R postgres:postgres $POSTGRESQL_DIR
+    sudo grep -q "^data_directory[[:blank:]]*=*[[:blank:]]*"  $POSTGRESQL_CONF_PATH && sudo sed "s|^data_directory[[:blank:]]*=*[[:blank:]]*.*|data_directory = \x27$POSTGRESQL_DATA_DIR\x27|" -i $POSTGRESQL_CONF_PATH ||  sudo sed "$ adata_directory = \x27$POSTGRESQL_DATA_DIR\x27" -i $POSTGRESQL_CONF_PATH
+    su postgres -c "/usr/lib/postgresql/13/bin/initdb -D $POSTGRESQL_DATA_DIR"
+    pg_ctlcluster 13 main restart
+  fi
+fi
+
+if [ "$os_id" = centos ]; then
+  if which psql >/dev/null; then 
+    echo "Postgresql is already intalled";    
+    if [[ ! -f "$POSTGRESQL_DATA_DIR/PG_VERSION" ]]; then
+        chown -R postgres:postgres $POSTGRESQL_DIR
+        sudo systemctl stop  postgresql-10
+        sed -i "s~^Environment=PGDATA=.*~Environment=PGDATA=$POSTGRESQL_DATA_DIR~" /usr/lib/systemd/system/postgresql-10.service
+        sudo systemctl daemon-reload
+        /usr/pgsql-10/bin/postgresql-10-setup initdb
+        sudo systemctl restart postgresql-10
+    fi
+  else
+    yum install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
+    yum install -y postgresql10-server python-psycopg2 hunspell-en-US
+    chown -R postgres:postgres $POSTGRESQL_DIR
+    sed -i "s~^Environment=PGDATA=.*~Environment=PGDATA=$POSTGRESQL_DATA_DIR~" /usr/lib/systemd/system/postgresql-10.service
+    sudo systemctl daemon-reload
+    /usr/pgsql-10/bin/postgresql-10-setup initdb
+    sudo systemctl restart postgresql-10
+  fi
+fi
+
+if [ "$os_id" = centos ]; then
+  echo "########### firewall config for rabbitmq  ############"
+  rpm  -i --force  "$ZULIP_PATH"/packages/sys-deps/firewalld-0.6.3-13.el7_9.noarch.rpm
+  sudo firewall-cmd --permanent --add-port=5672/tcp
+  sudo firewall-cmd --reload
+  sudo systemctl stop firewalld
+  sudo systemctl start firewalld
+  sudo setenforce 0
 fi
 
 if has_class "zulip::app_frontend_base"; then
@@ -590,6 +696,47 @@ EOF
     fi
 fi
 
+# generate ZIMBRA_JWT_AUTH_KEY
+sudo grep -q "^ZIMBRA_JWT_AUTH_KEY[[:blank:]]*=*[[:blank:]]*"  /etc/zulip/settings.py \
+    || (JWT_AUTH_KEY=$(cat /dev/urandom | tr -cd 'a-f0-9' | head -c 32);  sudo sed "$ a\ZIMBRA_JWT_AUTH_KEY = \x27$JWT_AUTH_KEY\x27\n" -i /etc/zulip/settings.py)
+
+
+if [ ! -z $LDAP_SERVER ]; then
+
+    if [ ! -z $LDAP_SERVER_PORT ] && [ $LDAP_SERVER_PORT != "389" ]; then
+        LDAP_SERVER_URL="$LDAP_SERVER:$LDAP_SERVER_PORT"
+    else
+        LDAP_SERVER_URL=$LDAP_SERVER
+    fi
+
+    sudo grep -q "^AUTH_LDAP_SERVER_URI[[:blank:]]*=*[[:blank:]]*" /etc/zulip/settings.py \
+        && sudo sed "s/^AUTH_LDAP_SERVER_URI[[:blank:]]*=*[[:blank:]]*.*/AUTH_LDAP_SERVER_URI = \x27$LDAP_PROTOCOL:\/\/$LDAP_SERVER_URL\x27/" -i /etc/zulip/settings.py \
+        || sudo  sed "$ a\AUTH_LDAP_SERVER_URI = \x27$LDAP_PROTOCOL:\/\/$LDAP_SERVER_URL\x27" -i /etc/zulip/settings.py
+fi
+
+if [ ! -z $LDAP_PASSWORD ]; then
+    sudo grep -q "^auth_ldap_bind_password[[:blank:]]*=*[[:blank:]]*" /etc/zulip/zulip-secrets.conf \
+        && sudo sed "s/^auth_ldap_bind_password[[:blank:]]*=*[[:blank:]]*.*/auth_ldap_bind_password = $LDAP_PASSWORD/" -i  /etc/zulip/zulip-secrets.conf \
+        || sudo  sed "$ a\auth_ldap_bind_password = $LDAP_PASSWORD" -i  /etc/zulip/zulip-secrets.conf
+fi
+
+if [ ! -z $LDAP_BIND_DN ]; then
+    sudo grep -q "^AUTH_LDAP_BIND_DN[[:blank:]]*=*[[:blank:]]*" /etc/zulip/settings.py \
+        && sudo sed "s/^AUTH_LDAP_BIND_DN[[:blank:]]*=*[[:blank:]]*.*/AUTH_LDAP_BIND_DN = \x27$LDAP_BIND_DN\x27/" -i /etc/zulip/settings.py \
+        || sudo  sed "$ a\AUTH_LDAP_BIND_DN = \x27$LDAP_BIND_DN\x27" -i /etc/zulip/settings.py
+fi
+
+if [ "$os_id" = centos ]; then
+    chown -R zulip:zulip /var/lib/nginx
+    systemctl enable postgresql-10
+    systemctl enable rabbitmq-server
+    systemctl enable redis
+    systemctl enable memcached
+    systemctl enable supervisord
+    systemctl enable nginx
+    sed -i 's~^SELINUX=.*~SELINUX=permissive~'  /etc/selinux/config
+fi
+
 if has_class "zulip::profile::rabbitmq"; then
     if ! rabbitmqctl status >/dev/null; then
         set +x
@@ -629,14 +776,16 @@ if has_class "zulip::app_frontend_base"; then
     fi
 fi
 
+
 # Set up a basic .gitconfig for the 'zulip' user
-if [ -n "$ZULIP_ADMINISTRATOR" ]; then
-    (
-        cd / # Make sure the current working directory is readable by zulip
-        su zulip -c "git config --global user.email $ZULIP_ADMINISTRATOR"
-        su zulip -c "git config --global user.name 'Zulip Server ($EXTERNAL_HOST)'"
-    )
-fi
+(
+    cd / # Make sure the current working directory is readable by zulip
+    su zulip -c "git config --global user.email $ZULIP_ADMINISTRATOR"
+    su zulip -c "git config --global user.name 'Zulip Server ($EXTERNAL_HOST)'"
+)
+
+# copy settings
+cp -a /etc/zulip/. /opt/zimbra/data/zulip/conf/
 
 if [ -n "$NO_INIT_DB" ]; then
     set +x
